import app from './app.ts';
import request from 'supertest';
import { beforeEach, describe, expect, it, vi } from 'vitest';

const mode = process.env.TEST_MODE;
const shouldRunMock = !mode || mode  === 'ALL' || mode === 'MOCK';
const shouldRunApi = mode === 'ALL' || mode === 'API';

// General tests for both modes
describe('POST /api/assistant', () => {
    it('returns 415 when Content-Type is not application/json', async () => {
        const res = await request(app)
            .post('/api/assistant')
            .set('Content-Type', 'text/plain')
            .send('Vintage leather jacket');
        expect(res.status).toBe(415);
        expect(res.text).toBe('Content-Type must be application/json');
    });

    it('returns 400 when description is missing from body', async () => {
        const res = await request(app)
            .post('/api/assistant')
            .send({});
        expect(res.status).toBe(400);
        expect(res.text).toBe("The request body must be an object containing a non-empty 'description' string.");
    });

    it('returns 400 when description is not a string', async () => {
        const res = await request(app)
            .post('/api/assistant')
            .send({ description: 12345 });
        expect(res.status).toBe(400);
        expect(res.text).toBe("The request body must be an object containing a non-empty 'description' string.");
    });

    it('returns 400 when description is empty string or only whitespace', async () => {
        const emptyRes = await request(app)
            .post('/api/assistant')
            .send({ description: '' });
        expect(emptyRes.status).toBe(400);

        const whitespaceRes = await request(app)
            .post('/api/assistant')
            .send({ description: '   \n\t  ' });
        expect(whitespaceRes.status).toBe(400);
    });
});

// Specific tests for MOCK mode
describe.runIf(shouldRunMock)('POST /api/assistant (MOCK)', () => {
    beforeEach(() => {
        vi.stubEnv('MODE', 'MOCK');
    });

    it('returns a valid ListingResponse from mock provider for a known item', async () => {
        const res = await request(app)
            .post('/api/assistant')
            .send({ description: 'Vintage leather jacket, worn once, size M' });
        expect(res.status).toBe(200);
        expect(res.body.title).toBe('Vintage Black Leather Jacket - Size M - Excellent Condition');
        expect(res.body.tags).toBeInstanceOf(Array);
        expect(res.body.minPrice).toBe(45);
        expect(res.body.maxPrice).toBe(85);
    });

    it('returns 502 when mock provider encounters a malformed response', async () => {
        const res = await request(app)
            .post('/api/assistant')
            .send({
                description:
                    'Nintendo Switch OLED white model with Mario Kart 8 and Super Smash Bros, barely used, comes with carrying case',
            });
        expect(res.status).toBe(502);
    });

    it('returns 502 when mock provider returns response violating price logic (minPrice > maxPrice)', async () => {
        const res = await request(app)
            .post('/api/assistant')
            .send({
                description: 'Ikea desk lamp, working perfectly, minor scratch on base',
            });
        expect(res.status).toBe(502);
    });

    it('returns 500 when mock provider throws a simulated upstream error', async () => {
        const res = await request(app)
            .post('/api/assistant')
            .send({
                description: 'Old bicycle for parts, flat tires, rusty chain',
            });
        expect(res.status).toBe(500);
    });
});

// Specific tests for API mode
describe.runIf(shouldRunApi)('POST /api/assistant (API)', () => {
    beforeEach(() => {
        vi.stubEnv('MODE', 'API');
    });

    it('returns a valid ListingResponse generated by Gemini API', async () => {
        const res = await request(app)
            .post('/api/assistant')
            .send({ description: 'Vintage Black Leather Jacket, worn once, Size M' });
        expect(res.status).toBe(200);
        expect(typeof res.body.title).toBe('string');
        expect(Array.isArray(res.body.tags)).toBe(true);
        expect(typeof res.body.minPrice).toBe('number');
        expect(typeof res.body.maxPrice).toBe('number');
        expect(res.body.minPrice).toBeLessThanOrEqual(res.body.maxPrice);
    }, 25000);
});